name: Build Kernel
on: 
    workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Clang
          uses: KyleMayes/install-llvm-action@v2
          with: 
            version: 20
            directory: ./clang

        - name: Patch SukiSU
          run: |
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            echo "# CONFIG_KSU_MANUAL_HOOK is not set" >> "arch/arm64/configs/gki_defconfig"
            echo "CONFIG_KSU=y" >> "arch/arm64/configs/gki_defconfig"
            echo "CONFIG_KPROBES=y" >> "arch/arm64/configs/gki_defconfig"
            echo "CONFIG_HAVE_KPROBES=y" >> "arch/arm64/configs/gki_defconfig"
            echo "CONFIG_KPROBE_EVENTS=y" >> "arch/arm64/configs/gki_defconfig"

        - name: Patch susfs
          run: |
            git clone https://gitlab.com/simonpunk/susfs4ksu.git --single-branch --branch gki-android13-5.15
            cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch ./
            cp susfs4ksu/kernel_patches/fs/* ./fs/
            cp susfs4ksu/kernel_patches/include/linux/* ./include/linux/
            patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch
            echo "CONFIG_KSU_SUSFS=y" >> "arch/arm64/configs/gki_defconfig"

        - name: Install libelf🤔
          uses: ConorMacBride/install-package@v1
          with:
            apt: libelf-dev

        - name: Build Kernel
          run: |
            export PATH="./clang/clang-r547379/bin:$PATH"
            export ARCH=arm64
            export SUBARCH=arm64
            export CC=clang
            export LD=ld.lld
            export AR=llvm-ar
            export HOSTCC=clang
            export HOSTCXX=clang++
            export HOSTLD=ld.lld
            export HOSTAR=llvm-ar
            export CROSS_COMPILE=aarch64-linux-gnu-
            export CLANG_TRIPLE=aarch64-linux-gnu-
            export LLVM=1
            export KCDFLAGS=-flto=thin
            make O=out arch/arm64/configs/defconfig gki_defconfig
            make O=out -j$(nproc --all) | tee kernel_log.log

        - name: Upload to artifact
          uses: actions/upload-artifact@v4
          with:
            name: kernel-Build
            path: out/arch/arm64/boot/Image*
        
